### ISSUE TITLE
Improve load_balancing documentation

### ISSUE THREAD

**Issue by mapno** [grafana/agent#1673]
Load balacing is a feature of the trace subsystem of the Agent. It is used to load balance traces among an Agent deployment so spans that belong to the same trace are grouped in the same instance. This is important for certain processors, such as service graphs and tail sampling.

Load balancing is an advanced feature and can be difficult to set up. Documentation around it should be improved. Some improvements are:

## TODOs

- [x] Document missing `receiving_port` config option (https://github.com/grafana/agent/pull/1672)
- [ ] Expand on headless service requirement when running on kubernetes
- [ ] Add examples where load_balancing is enabled (docker, tk, etc)
