### ISSUE TITLE
Flow: squash blocks where appropriate 

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#2985]
Up until #2934 was merged, Flow components didn't support block squashing. This means for any Flow component which wraps around some upstream logic, we had to introduce fields as blocks even if the upstream component itself used squashing. 

For example, Prometheus remote_write is configured where the HTTP client configuration is squashed into the remote_write endpoint:

```yaml
remote_write:
  - basic_auth: # Squashed from HTTP client configuration
      username: foo 
      password_file: /etc/secrets/foo 
```

But we had to add an extra layer of indirection for `prometheus.remote_write`: 

```river 
prometheus.remote_write "example" {
  endpoint {
    http_client_config {
      username      = "foo"
      password_file = "/etc/secrets/foo"
    }
  }
}
```

Now that #2934 is available, we can clean up these blocks, squashing things where the upstream counterpart is also squashing. 

This issue tracks the list of components that need to be updated. 

Note that this is a **breaking change**, so it's good to get these all in sooner rather than later, while the Flow adoption is still slowly growing. 

```[tasklist]
### Tasks
- [ ] https://github.com/grafana/agent/issues/2986
- [ ] https://github.com/grafana/agent/issues/2987
- [ ] https://github.com/grafana/agent/issues/2988
- [ ] https://github.com/grafana/agent/issues/2989
- [ ] https://github.com/grafana/agent/issues/2990
- [ ] https://github.com/grafana/agent/issues/2991
- [ ] https://github.com/grafana/agent/issues/2992
- [ ] https://github.com/grafana/agent/issues/2993
- [ ] https://github.com/grafana/agent/issues/2994
- [ ] https://github.com/grafana/agent/issues/2995
- [ ] https://github.com/grafana/agent/issues/2996
- [ ] https://github.com/grafana/agent/issues/2997
- [ ] https://github.com/grafana/agent/issues/2998
```

To me, squashing makes sense when:

* The block hierarchy is more than two levels deep (such as `prometheus.remote_write > client > http_client_config`).
* The upstream configuration equivalent is squashing the field, but we're not.
* The block being squashed shares responsibility with the parent block (e.g., the responsibility of `prometheus.remote_write > client` and `prometheus.remote_write > client > http_client_config`) have a significant amount of overlap. 

We might want to avoid squashing when:

* The block hierarchy is shallow enough that writing the blocks isn't too tedious.  
* The block acts as a clear separation of concerns from its parent block.

**Comment by rfratto** [comment]
This is done now. Thanks @erikbaranowski and @ptodev!
