### ISSUE TITLE
Improve memory usage

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#3]
Memory usage of the agent for ~30K series is around 350MB megabytes of in-use heap memory. We should try as much as we can to investigate where that memory usage is coming from and what can be done to improvement. This will likely have to be done in a temporary fork of Prometheus before the memory improvements can be reintroduced upstream.

**TODO**

- [ ] Provide a more detailed analysis of memory vs Prometheus and Cortex 
- [ ] Provide a more detailed description of where memory problems lie 
- [ ] Create more issues to track specific areas where memory usage can be improved.

Image of memory usage comparing Cortex, the agent, and Prometheus, where both the agent and Prometheus are scraping the same sources:

![Memory stats](https://user-images.githubusercontent.com/630212/74376117-90ab9180-4daf-11ea-87d6-c8f23c9822ce.png)

**Comment by rfratto** [comment]
Without a particular memory usage target, this ticket would just sit here forever. On that note, I'm going to close this since we've made some improvements since the ticket was first created (as I mentioned in my previous comment). I've been happy with where we left off and there doesn't seem to be a lot of low hanging fruit remaining for the Agent to take advantage of.
