### ISSUE TITLE
Port over integrations into Flow components

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#3160]
This issue tracks porting over all integrations in static mode as Flow components.

It's not clear if there needs to be an "agent" integration in Flow, since you can have the agent scrape itself easily without defining one. 

```[tasklist]
### Tasks
- [ ] #1684
- [ ] #1685
- [ ] #2303  
- [ ] #2304  
- [ ] #2305  
- [ ] #2306 
- [ ] #2307 
- [ ] #2308 
- [ ] #2309 
- [ ] #2310 
- [ ] #2311 
- [ ] #2312 
- [ ] #2313 
- [ ] #2314 
- [ ] #2315 
- [ ] #2316 
- [ ] #2318
- [ ] #2320 
- [ ] #2322 
- [ ] https://github.com/grafana/agent/issues/3161
- [ ] https://github.com/grafana/agent/issues/3162
- [ ] https://github.com/grafana/agent/issues/3163
- [ ] https://github.com/grafana/agent/issues/3164
- [ ] https://github.com/grafana/agent/issues/3165
- [ ] https://github.com/grafana/agent/issues/3166
- [ ] https://github.com/grafana/agent/issues/3167
- [x] Flow component for eventhandler integration
- [ ] https://github.com/grafana/agent/issues/5021
```

**Comment by rfratto** [comment]
With #5314 merged, this issue can finally be closed 🎉
