### ISSUE TITLE
Remove exporter's forks

### ISSUE THREAD

**Issue by marctc** [grafana/agent#3413]
Currently we are using `replace` directive in `go.mod` for a specific subset of Prometheus exporters.
These forks were initially created to make them work with the Agent as some of the exporters need to be configure via command line flag (like windows exporter) or don't provide a way to initialize a collector from an external package.

The main problem is that the forks get outdated at some point, making harder to keep up to date (merge upstream dependencies is not always easier) and frequently unattended.

We should work with upstream exporters to port changes there (whenever is possible). These are the following exporters that need to be addressed:

```[tasklist]
### Tasks
- [ ] Get changes of `oracledb_exporter` merged upstream and remove `replace` in go.mod
- [ ] Get changes of `oracledb_exporter` merged upstream and remove `replace` in go.mod
- [ ] Get changes of `oracledb_exporter` merged upstream and remove `replace` in go.mod
- [ ] Get changes of `oracledb_exporter` merged upstream and remove `replace` in go.mod
- [ ] Get changes of `oracledb_exporter` merged upstream and remove `replace` in go.mod
- [ ] Get changes of `oracledb_exporter` merged upstream and remove `replace` in go.mod
- [ ] Get changes of `oracledb_exporter` merged upstream and remove `replace` in go.mod
```

**Comment by rfratto** [comment]
Hi there :wave: 

On April 9, 2024, Grafana Labs announced [Grafana Alloy](https://github.com/grafana/alloy), the spirital successor to Grafana Agent and the final form of Grafana Agent flow mode. As a result, Grafana Agent has been deprecated and will only be receiving bug and security fixes until its end-of-life around November 1, 2025. 

To make things easier for maintainers, we're in the process of migrating all issues tagged variant/flow to the Grafana Alloy repository to have a single home for tracking issues. This issue is likely something we'll want to address in both Grafana Alloy and Grafana Agent, so just because it's being moved doesn't mean we won't address the issue in Grafana Agent :)
