### ISSUE TITLE
Support converting other config files to Flow files

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#3659]
As Flow gains adoption, supporting config conversions from various tools which have rough feature parity with Flow will help users migrate to Flow. 

Conversion should be best-effort, if something configured in the source config does not have an equivalent in Flow, the conversion should generate either a warning or an error. 

Conversion should be defined for anything that exists in Flow which has a reasonable equivalent in the source config file. 

After conversion exists, we should update the PR template to remind authors to update the conversion code, if relevant to the new component. 

```[tasklist]
### Tasks
- [ ] https://github.com/grafana/agent/issues/3736
- [ ] https://github.com/grafana/agent/issues/3902
- [ ] https://github.com/grafana/agent/issues/3901
- [ ] https://github.com/grafana/agent/issues/3917
- [ ] https://github.com/grafana/agent/issues/3988
- [ ] https://github.com/grafana/agent/issues/3900
- [ ] https://github.com/grafana/agent/issues/3737
- [ ] https://github.com/grafana/agent/issues/3738
- [ ] https://github.com/grafana/agent/issues/4073
- [ ] https://github.com/grafana/agent/issues/4018
- [ ] https://github.com/grafana/agent/issues/6419
- [ ] https://github.com/grafana/agent/issues/4292
- [ ] https://github.com/grafana/agent/issues/4291
- [ ] https://github.com/grafana/agent/issues/4444
- [ ] https://github.com/grafana/agent/issues/6591
```
