### ISSUE TITLE
Sync loki.process with Promtail 2.8.4

### ISSUE THREAD

**Issue by tpaschalis** [grafana/agent#4836]

**Comment by tpaschalis** [comment]
Looking at the list of commits since October 2022 in Loki's `clients/pkg/logentry` package and the original inception of the loki.process components, here are the commits that _may_ want some extra work to be ported over.

- [X] 7d5475541 promtail: enable structured_metadata convert labels (#10752)
- [ ] f51ee849b fix(promtail): correctly parse list of drop stage sources from YAML (#10848)
- [X] 00a3c5b02 renamed `non indexed labels` feature to `structured metadata` (#10432)
- [X] bde65667f Upgrade dskit to use packages migrated from weaveworks/common (#10164)
- [X] 0fc934e4e non_indexed_labels stage: additional test-case (#10170)
- [X] 416e01ca8 [promtail] non_indexed_labels stage (#9986)
- [ ] 2dfac7283 Clarify that label filter expressions are not supported in promtail. (#9894)
- [X] 8abe080fd Promtail: improve behavior of partial lines (#9508)
- [X] 4a5644568 Upgrade `golangci-lint` and fix linting errors (#9601)
- [ ] 520e43444 (origin/k149) fix function names in comments (#9415)
- [X] 0295fd469 [new feature] promtail: Add a Promtail stage for probabilistic sampling (#7127)
- [ ] 540380fa9 Promtail: fix GeoIP typo (#8783)
- [X] e2ac2d50e Changes from linter (#8769)
- [X] b94c8aaf1 feature: geoip stage in promtail (#3493)
- [X] 43a21eac0 fix(promtail): Make `cri` tags streams aware. (#8497)
- [X] 85b3e5d4a Promtail: Add event log message stage (#8382)
- [ ] ee1aee0af feat(promtail): add more complex options of dropping logs at the drop stage (#6371)
- [ ] 02e0b3ae8 Fix logentry drop to more intuitively match numeric fields (fixes #7011) (#7292)
- [ ] d5b68c025 fix(promtail): Fix cri tags extra new lines. (#7997)
- [X] b773a7a3c promtail: ratelimiting by label (#7597)
- [X] c5911d534 Loki: implement decolorize filter (#7602)

**Comment by tpaschalis** [comment]
Continuing on the items left above

- [X] d5b68c025 fix(promtail): Fix cri tags extra new lines. (#7997) --- already fixed by https://github.com/grafana/agent/commit/7b40be346208d263a356887cf50ab1d99caf664e
- [X] 02e0b3ae8 Fix logentry drop to more intuitively match numeric fields (fixes #7011) (#7292) --- superseded by https://github.com/grafana/agent/commit/dbec50ff1b3aded3b1606fac1a818394f7941701
- [X] ee1aee0af feat(promtail): add more complex options of dropping logs at the drop stage (#6371) --- already fixed by https://github.com/grafana/agent/commit/dbec50ff1b3aded3b1606fac1a818394f7941701
- [X] 540380fa9 Promtail: fix GeoIP typo (#8783) --- fixing in this branch 9e6f1ca0cc0fffcca68229d2e9a8e660cb3b0625
- [X] 520e43444 (origin/k149) fix function names in comments (#9415) --- fixing in upcoming PR ca61247374c360be7861810bf3788819e11909c7
- [X] 2dfac7283 Clarify that label filter expressions are not supported in promtail. (#9894) --- fixing in upcoming PR 31cf85f7100d06aa6278559b4f90ac58ed6ffdb4
- [X] f51ee849b fix(promtail): correctly parse list of drop stage sources from YAML (#10848) --- superseded by https://github.com/grafana/agent/commit/dbec50ff1b3aded3b1606fac1a818394f7941701
