### ISSUE TITLE
Integration tests: next steps

### ISSUE THREAD

**Issue by wildum** [grafana/agent#5613]
```[tasklist]
### Tasks
- [ ] Consider using [test containers](https://github.com/testcontainers/testcontainers-go)
- [ ] Add new tests: modules, k3d, integrations, exporter
- [ ] Consider a better way to generate Otel metrics (we currently use a demo-server and demo-client copied from [opentelemetry-collector-contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/examples/demo), maybe we could import it instead of copying it?)
```
