### ISSUE TITLE
Agent documentation enhancements tracking

### ISSUE THREAD

**Issue by thampiotr** [grafana/agent#5778]
### Tracking issue

This issue is used for a set of Agent Flow documentation enhancements, which we're planning to complete around Q4 2023.

Full scope is currently under discussion and will be added in the near future.

```[tasklist]
### Tasks
- [ ] https://github.com/grafana/agent/issues/4754
- [ ] https://github.com/grafana/agent/issues/5949
- [ ] https://github.com/grafana/agent/issues/5950
- [ ] https://github.com/grafana/agent/pull/5888
- [ ] https://github.com/grafana/agent/issues/5947
- [ ] https://github.com/grafana/agent/issues/5959
- [ ] https://github.com/grafana/agent/issues/5962
- [ ] https://github.com/grafana/agent/issues/5961
- [ ] https://github.com/grafana/agent/issues/5960
- [ ] https://github.com/grafana/agent/pull/5793
- [ ] https://github.com/grafana/agent/issues/5207
- [ ] https://github.com/grafana/agent/issues/5214
```
